GUN_APP_NAME = "GUN CLUB"

GUN_NAVY = "#0C233F"
GUN_GREY = "#9EA2A3"
GUN_WHITE = "#FFFFFF"
GUN_LIGHT_GREY = "#F4F5F6"
GUN_RED = "#B00020"
GUN_GREEN = "#167A3A"

GUN_LOGO_PATH = "gun_assets/gun_club_logo.jpeg"
GUN_HEADER_FONT_PATH = "gun_assets/ITC_Newtext_Demi.ttf"
GUN_BODY_FONT_PATH = "gun_assets/FrutigerLTStd-Black.otf"

GUN_QUOTE = '"THE TIME WILL COME WHEN WINTER WILL ASK WHAT YOU WERE DOING ALL SUMMER."'
